
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int especial = 2;
  public static final int suma = 17;
  public static final int ampersand = 12;
  public static final int pestan = 36;
  public static final int letraexp = 3;
  public static final int corchetescierra = 29;
  public static final int barravertical = 34;
  public static final int llavesabre = 33;
  public static final int coma = 6;
  public static final int igual = 24;
  public static final int identificador = 37;
  public static final int letra = 38;
  public static final int numeral = 9;
  public static final int llavescierra = 35;
  public static final int comillasimple = 13;
  public static final int menos = 18;
  public static final int menor = 23;
  public static final int porcentaje = 11;
  public static final int EOF = 0;
  public static final int comilladoble = 7;
  public static final int error = 1;
  public static final int mayor = 25;
  public static final int entero = 39;
  public static final int parentesisabre = 14;
  public static final int punto = 19;
  public static final int dospuntos = 21;
  public static final int barrainclinada = 20;
  public static final int parentesiscierra = 15;
  public static final int guionbajo = 31;
  public static final int elevado = 30;
  public static final int conj = 5;
  public static final int arroba = 27;
  public static final int puntocoma = 22;
  public static final int casc = 42;
  public static final int dolar = 10;
  public static final int casb = 41;
  public static final int casa = 40;
  public static final int asterisco = 16;
  public static final int corchetesabre = 28;
  public static final int admiracion = 8;
  public static final int acentograve = 32;
  public static final int interrogacion = 26;
  public static final int cadena = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "especial",
  "letraexp",
  "cadena",
  "conj",
  "coma",
  "comilladoble",
  "admiracion",
  "numeral",
  "dolar",
  "porcentaje",
  "ampersand",
  "comillasimple",
  "parentesisabre",
  "parentesiscierra",
  "asterisco",
  "suma",
  "menos",
  "punto",
  "barrainclinada",
  "dospuntos",
  "puntocoma",
  "menor",
  "igual",
  "mayor",
  "interrogacion",
  "arroba",
  "corchetesabre",
  "corchetescierra",
  "elevado",
  "guionbajo",
  "acentograve",
  "llavesabre",
  "barravertical",
  "llavescierra",
  "pestan",
  "identificador",
  "letra",
  "entero",
  "casa",
  "casb",
  "casc"
  };
}

